Module6 task1
htmlacademy-react/1394423-six-cities-10 pull request #10
Opened 2022-08-26 13:25 UTC by c0xa

2022-08-28 17:29 UTC, MrMeison requested changes

2022-08-28 17:29 UTC, MrMeison commented on project/src/index.tsx
> +  cityList: cityList,
После перехода на redux можно там хранить все эти данные и не пробрасывать пропсы, а получать через useAppSelector и useAppDispatch

2022-08-28 17:29 UTC, MrMeison commented on project/src/pages/property/property.tsx
> +  const {currentCity} = useAppSelector((state) => state);
а тут точно правильный селектор?

2022-08-28 17:29 UTC, MrMeison commented on project/src/pages/welcome-screen/welcome-screen.tsx
> +  const {currentCity, offers} = useAppSelector((state) => state);
может стоит сделать точечные селекторы, а не общий для получения всего состояния?

2022-08-29 10:41 UTC, c0xa commented on project/src/pages/welcome-screen/welcome-screen.tsx
> +  const {currentCity, offers} = useAppSelector((state) => state);
done

2022-08-29 10:41 UTC, c0xa commented on project/src/index.tsx
> +  cityList: cityList,
done

2022-08-30 07:09 UTC, MrMeison commented on project/src/pages/welcome-screen/welcome-screen.tsx
> +  offers?.forEach((cardValue) => positions.push(cardValue.position));
1. `forEach` → `map`.
2. вынести в отдельный селектор `useAppSelector((state) => state.offers.map(offer => offer. position))`
const getOffers = (state) => state.offers;
const getPositions = createSelector(getOffers, (offers) => offers.map(offer => offer. position));

2022-08-30 07:13 UTC, MrMeison commented on project/src/pages/welcome-screen/welcome-screen.tsx
> +  offers?.forEach((cardValue) => positions.push(cardValue.position));
```js
const getOffers = (state) => state.offers;
const getCurrentCity = (state) => state.currentCity;
const getOffersByCity = createSelector(getOffers, getCurrentCity, (offers, city) => offers.filter(offer => offer. city === city));
```

2022-08-30 07:25 UTC, merged