Module2 task1
htmlacademy-react/1394423-six-cities-10 pull request #3
Opened 2022-07-12 17:21 UTC by c0xa

2022-07-13 18:46 UTC, MrMeison requested changes

2022-07-13 18:46 UTC, MrMeison commented on project/src/components/app/app.tsx
> +function App(prop: WelcomePageProps): JSX.Element {
Обычно используют:
1. function expression для описания компонента
2. `prop` → `props` так как их все таки "много"

```suggestion
const App = (props: WelcomePageProps): JSX.Element  => {
```

2022-07-13 18:46 UTC, MrMeison commented on project/src/components/city-card/city-card.tsx
> +import {Card} from '../../types/card/card';
Кажется в последних версиях ts можно написать `import type ...` для того чтобы явно описать что импортируются исключительно типы. Это полезно, для того чтобы не смешивать логику и типы, и немного помочь ts, более быстро работать

2022-07-13 18:46 UTC, MrMeison commented on project/src/components/city-card/city-card.tsx
> +function CityCard(props: {card: Card}): JSX.Element {
Правильнее было бы передавать не сложный тип в одном пропсе, а деструктуризированную версию. Это поможет более эффективно использовать `React.memo` в дальнейшем, который как раз сравнивает [поверхностно](https://ru.reactjs.org/docs/react-api.html#reactmemo)

2022-07-13 18:46 UTC, MrMeison commented on project/src/components/city-cards/city-cards.tsx
> +const cityCards: Card[] = [
почему бы не вынести моки отдельно и не добавить id, для более явного указания key?

2022-07-13 18:46 UTC, MrMeison commented on project/src/components/city-cards/city-cards.tsx
> +    nameCard: 'Wood and stone place',
Повторение именования сущности в свойстве сущности. Можно просто `name`

2022-07-13 18:46 UTC, MrMeison commented on project/src/types/card/card.ts
> +export type Card = {
Можно в принципе так сильно не дробить — вынести типы в один файл. Если понадобиться в дальнейшим или станет сложно навигироваться — можно побить на файлики.

2022-07-16 08:49 UTC, c0xa commented on project/src/components/city-cards/city-cards.tsx
> +    nameCard: 'Wood and stone place',
nameCard -> name
typeCard -> type

2022-07-16 13:06 UTC, c0xa commented on project/src/types/card/card.ts
> +export type Card = {
card and prop => properties

2022-07-16 13:07 UTC, c0xa commented on project/src/components/city-card/city-card.tsx
> +import {Card} from '../../types/card/card';
done

2022-07-16 13:07 UTC, c0xa commented on project/src/components/app/app.tsx
> +function App(prop: WelcomePageProps): JSX.Element {
done

2022-07-17 07:27 UTC, c0xa commented on project/src/components/city-cards/city-cards.tsx
> +const cityCards: Card[] = [
done

2022-07-17 18:54 UTC, c0xa commented on project/src/components/city-card/city-card.tsx
> +function CityCard(props: {card: Card}): JSX.Element {
used a spread operator

2022-07-18 18:12 UTC, merged